### ISSUE TITLE
AWS_IO_DNS_INVALID_NAME

### ISSUE THREAD

**Issue by casperthuis** [awslabs/amazon-transcribe-streaming-sdk#39]
Hi all,

First of all thanks for creating this repo, its very helpful. 
Im trying to get the examples running, however without much success yet. 

I get the following error from the assert package, while I guess I filled in all the variables correctly.

`
% python simple_file.py
<amazon_transcribe.client.TranscribeStreamingClient object at 0x7f84f2ab4ca0>
Traceback (most recent call last):
  File "/Users/casperthuis/amazon-transcribe-streaming-sdk/examples/simple_file.py", line 56, in <module>
    loop.run_until_complete(basic_transcribe())
  File "/Users/casperthuis/opt/anaconda3/envs/transcription-api/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/casperthuis/amazon-transcribe-streaming-sdk/examples/simple_file.py", line 34, in basic_transcribe
    stream = await client.start_stream_transcription(
  File "/Users/casperthuis/opt/anaconda3/envs/transcription-api/lib/python3.9/site-packages/amazon_transcribe/client.py", line 155, in start_stream_transcription
    response = await session.make_request(
  File "/Users/casperthuis/opt/anaconda3/envs/transcription-api/lib/python3.9/site-packages/amazon_transcribe/httpsession.py", line 196, in make_request
    connection = await self._get_connection(parsed_url)
  File "/Users/casperthuis/opt/anaconda3/envs/transcription-api/lib/python3.9/site-packages/amazon_transcribe/httpsession.py", line 164, in _get_connection
    connection = await self._create_connection(parsed_url)
  File "/Users/casperthuis/opt/anaconda3/envs/transcription-api/lib/python3.9/site-packages/amazon_transcribe/httpsession.py", line 142, in _create_connection
    connection = await asyncio.wrap_future(connect_future)
awscrt.exceptions.AwsCrtError: AWS_IO_DNS_INVALID_NAME: Host name was invalid for dns resolution.
`

I'm a bit lost here. It might be that one of you have already seen this and knows a good direction to search in. 

Thanks in advance.

**Comment by casperthuis** [comment]
The problem was that I picked the wrong region.
